pca_descriptor:
	gcc -O3 pca_descriptor.c ../../../VISION/pca/pca.c ../../../VISION/features/pca/pca.c ../../../VISION/interface/interface.c  ../../../VISION/processing/free.c  -o pca_descriptor -lm -lgsl -lgslcblas
