hog_descriptor:
	gcc -O3 hog_descriptor.c ../../VISION/features/hog.c ../../VISION/interface/interface.c ../../VISION/processing/convolution.c ../../VISION/processing/free.c ../../VISION/processing/gradients.c ../../VISION/filters/diferencial.c ../../VISION/tools/histogram_equalizer.c -o hog_descriptor -lm
